name: CI

on:
  push:
    branches:
      - master
    paths:
      - '**.c'
      - '**.h'
      - '**.yml'

jobs:
  examples:
    runs-on: ubuntu-latest #[self-hosted, Linux, X64] #
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Checkout pico-sdk
        uses: actions/checkout@v3
        with:
          repository: raspberrypi/pico-sdk
          ref: develop
          path: RP2040/pico-sdk

      - name: pico-sdk submodules
        working-directory: RP2040/pico-sdk
        run: git submodule update --init

      - name: Install
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi cmake libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Build
        working-directory: RP2040/src/examples
        shell: bash
        run: |
          mkdir build && cd build
          PICO_SDK_PATH=../../pico-sdk cmake ..
          cmake .. && make

      - uses: actions/upload-artifact@v3
        with:
          name: examples
          path: RP2040/src/examples/build

  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: actions-rs
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: thumbv6m-none-eabi
          override: true

      - name: rp2040-pac build
        working-directory: RP2040/src/template/rp2040-pac
        run: |
          cargo build --release
